### ISSUE TITLE
关于文档和部署环境

### ISSUE THREAD

**Issue by ketoo** [liangliangyy/MVCBlog#1]
最近在学习mvcweb开发，对这个项目很感兴趣，作者是否可以加一个入门教程比如数据库配置的地方让初学者clone代码编译配置好然后就可以跑起来这样。O(∩_∩)O谢谢。

**Comment by liangliangyy** [comment]
实在是抱歉，这些代码是当时初学MVC时候写的，现在看来很多地方的实现还是有点欠妥，而且这个项目也好久没有更新了，最近在学习.Net Core，有想法用.Net Core来实现一个，新的项目文档等会更加完整，敬请期待。
